### ISSUE TITLE
small error in documentation

### ISSUE THREAD

**Issue by romunov** [diogocavilha/fancy-git#108]
Just noticed that separators are not documented properly. Notice that where it says `--separator-fire`, the image is actually for the curved separator. `--separator-paint` is missing the corresponding line.
I think that the default (first two lines) are identical and one could be removed.

![image](https://user-images.githubusercontent.com/544571/155096976-3518909a-0230-48e5-b509-7d7196b47454.png)

**Comment by diogocavilha** [comment]
Hi, @romunov 

Thank you for that. 
When I created that image, I thought it could be understood like...

`fancygit --separator-default [ENTER]`

`fancygit --separator-blocs [ENTER]`

`fancygit --separator-blocs-tiny [ENTER]`

and so on...

But you're right, maybe I should change that image to clarify it.

**Comment by romunov** [comment]
Huh, I didn't think it could be interpreted like that. Now that you've mentioned it, it does make sense.

**Comment by diogocavilha** [comment]
Hi, @romunov 

I've updated the readme file according to your comment. Now we have a better comprehension of what every separator style looks like.
