### ISSUE TITLE
make an option to show cursor on new line

### ISSUE THREAD

**Issue by sudhir600** [diogocavilha/fancy-git#115]
Because of the design and long git information.. there is less room for new commands in single row.
so it will be good if cursor start on new line like [this](https://user-images.githubusercontent.com/35486894/101484925-387de700-390f-11eb-8462-b562accf7ff1.png).

**Comment by diogocavilha** [comment]
Hi, @sudhir600 

Thank you so much for your suggestion.

FancyGit has already this feature.

You can run `fancygit --enable-double-line` and it'll transform the prompt.

Please, let me know if that is what you were looking for.

**Comment by sudhir600** [comment]
Thanks for letting me know. It worked now as expected.
