### ISSUE TITLE
NTH: aliases disabler flag (or better documentation about aliases)

### ISSUE THREAD

**Issue by mbeorlegui** [diogocavilha/fancy-git#119]
I alredy have my bash aliases, but the config with this beautiful prompt changer are stepped on...

So my proposal is todo a flag (something like `--toggle-aliases`, or `--enable-aliases` and `--disable-aliases`) for the people like me who enjoy this tool, but alredy have his own aliases.

Or just explain in the documentation how to edit this aliases, cause I couldn't find it.

Thanks for reading :)

**Comment by mbeorlegui** [comment]
Checking the code I find out that the aliases are in `.fancy-git/aliases`, but there's no good documentation about it.

**Comment by diogocavilha** [comment]
Hi, @mbeorlegui 

Oh! You have a good point here! Thank you for that. I'll improve the docs about aliases.
But please, let me know if you've already solved the problem.

**Comment by mbeorlegui** [comment]
Yeah, I solved it deleting some lines of the aliases files, but it had to do reverse engineering haha.
Thank you very much!

**Comment by diogocavilha** [comment]
I see. Indeed, if you have some aliases with the same name as FancyGit does, yours will be replaced by the the ones of FancyGit, once it is loaded last.

The other solution is to load fancygit prompt before loading your .bash_aliases, on your .bashrc file.

**Comment by mbeorlegui** [comment]
Yeah, that's a good idea too.

I'll close the issue. Thank you very much!
