### ISSUE TITLE
Add support for virtual environments

### ISSUE THREAD

**Issue by romunov** [diogocavilha/fancy-git#28]
Would it be possible to add which virtual environment is currently active (if at all)?

**Comment by diogocavilha** [comment]
Hi @romunov
Do you mean like python virtual environment?

**Comment by romunov** [comment]
@diogocavilha exactly.

**Comment by diogocavilha** [comment]
@romunov sorry for being late on replying! That's been really busy days this week at work.

Thank you for that issue. I'll be working on that next weekend.

**Comment by diogocavilha** [comment]
@romunov please let me know if it's working for you now.

**Comment by romunov** [comment]
Very nice. The only thing I noticed is that <venv> tag disappears once I enter a git repo. Here is an example:

![image](https://user-images.githubusercontent.com/544571/59907982-a6c5a580-940c-11e9-8db3-67f93ead57ef.png)

**Comment by romunov** [comment]
An idea would be to just indicate that you're in a virtual environment to preserve space. Maybe a cute icon at the beginning of a specific color. Something that represents something virtual, something abstract, something that's there, but not really. A ghost! Perhaps something like this? :) It's available in the fonts you currently use (at the end of the table).

![image](https://user-images.githubusercontent.com/544571/59918393-e3050000-9424-11e9-8a7e-6dc86197a648.png)

**Comment by diogocavilha** [comment]
> Very nice. The only thing I noticed is that tag disappears once I enter a git repo. Here is an example:
> 
> ![image](https://user-images.githubusercontent.com/544571/59907982-a6c5a580-940c-11e9-8db3-67f93ead57ef.png)

Woops! That's my fault. I'll be working on that.

> An idea would be to just indicate that you're in a virtual environment to preserve space. Maybe a cute icon at the beginning of a specific color. Something that represents something virtual, something abstract, something that's there, but not really. A ghost! Perhaps something like this? :) It's available in the fonts you currently use (at the end of the table).
> 
> ![image](https://user-images.githubusercontent.com/544571/59918393-e3050000-9424-11e9-8a7e-6dc86197a648.png)

Yep, I see your point. Wouldn't it be interesting to know the name of the virtual environment you're working on? I mean, isn't that used for anything else? The fact of knowing you're working on a virtual environment is enough? I'm asking you that because I don't have experience on python development yet, so I don't know how important is to know the name of the virtual environment.

If you tell me just an icon is enough, let's do this! =D

Thank you.

**Comment by romunov** [comment]
In order to have things comparable to other tools, displaying the name would be the way to go. But letting the ghost go is hard, so I would cheer for implementing just the icon for `fancygit simple` theme only. To have things more convenient for minimal theme users, perhaps you could bind a new command that would display current working virtual environment, something along the lines of what `pwd` does - perhaps a `pvd`?

**Comment by diogocavilha** [comment]
> In order to have things comparable to other tools, displaying the name would be the way to go. But letting the ghost go is hard, so I would cheer for implementing just the icon for `fancygit simple` theme only. To have things more convenient for minimal theme users, perhaps you could bind a new command that would display current working virtual environment, something along the lines of what `pwd` does - perhaps a `pvd`?

Hum I see. So I'm gonna implement the ghost icon for every fancygit theme that shows that colored bar. The other ones will really print the virtual environment name.

And the `pvd` command... yep, that's ok. I just need more time to think on how it would be written the best way. But, it will have a `g` at the begining, like `gpvd`, that's for keeping the fancygit aliases pattern.

So, could you open a new issue for that `gpvd` command? I'll treat it as another task.

**Comment by diogocavilha** [comment]
@romunov I can't find that ghost icon you said.

**Comment by romunov** [comment]
I saw it here:

![image](https://user-images.githubusercontent.com/544571/59959823-cc12ec00-94be-11e9-9a60-8d760fc7daae.png)

**Comment by romunov** [comment]
It would perhaps be prudent to add `pve` to the helpfile (maybe [here](https://github.com/diogocavilha/fancy-git/blob/master/help.sh#L44)?).

**Comment by diogocavilha** [comment]
> It would perhaps be prudent to add `pve` to the helpfile (maybe [here](https://github.com/diogocavilha/fancy-git/blob/master/help.sh#L44)?).

I don't get it.

**Comment by diogocavilha** [comment]
Oh! I've had added it to the end of aliases list. I don't know why it isn't there anymore. 
Maybe I've overwritten it

I'm gonna put it there again.

**Comment by romunov** [comment]
Happens to the best.

**Comment by diogocavilha** [comment]
My bad! I added it just on README file. It's on helper now.
