### ISSUE TITLE
problem with fonts

### ISSUE THREAD

**Issue by romunov** [diogocavilha/fancy-git#39]
After successfully installing fancygit to two machines, the third one is having problem. It's an out of the box Ubuntu 19.04 (English and UTF-8 encoding). The terminal is Konsole (Gnomoe terminal doesn't work because it doesn't display all the fonts). The icons appear to be truncated. This also happens when I view `fancygit --help` so it suggests that this is terminal/system issue. Have you encountered anything like this before?

![Screenshot from 2019-06-24 19-05-53](https://user-images.githubusercontent.com/544571/60037978-558b0f80-96b3-11e9-8833-4f44d1c961b4.png)

**Comment by diogocavilha** [comment]
Oh! This one is a new issue to me too.

I'll test this situation by using a VM. 
Maybe I could do something in order to fix that bug. Or, at least I'll try to understand what's going on.

**Comment by diogocavilha** [comment]
I've just researched for some similar problem when using konsole, and it really seems to be a terminal issue.

Take a look: https://github.com/Peltoche/lsd/issues/118

There's a link to this page too: https://bugs.kde.org/show_bug.cgi?id=390650

**Comment by diogocavilha** [comment]
This is a problem to mention on README file. I didn't know about that.

**Comment by romunov** [comment]
This worked in Konsole on Ubuntu 18.04. Too bad I already nuked the install and I can't verify which version I used.

**Comment by diogocavilha** [comment]
> This worked in Konsole on Ubuntu 18.04. Too bad I already nuked the install and I can't verify which version I used.

Oh really!? What a tricky bug!

**Comment by diogocavilha** [comment]
How about that version you're using now? What is it?

Another thing we could do is to open a ticket like this one: https://bugs.kde.org/show_bug.cgi?id=404128

I think I'm gonna do this later.

**Comment by diogocavilha** [comment]
Have you tried to use Terminator instead?
This is a good terminal option too.

**Comment by romunov** [comment]
Installed the latest version from [here](https://ubuntu.pkgs.org/19.04/kubuntu-backports-amd64/konsole_19.04.2-0ubuntu1~ubuntu19.04~ppa1_amd64.deb.html) and it works.

```
sudo add-apt-repository ppa:kubuntu-ppa/backports
sudo apt-get update
sudo apt-get install konsole
```

![Screenshot from 2019-06-24 19-40-44](https://user-images.githubusercontent.com/544571/60039923-21feb400-96b8-11e9-9674-b55c9dd18abb.png)

**Comment by diogocavilha** [comment]
Oh great!!!
