### ISSUE TITLE
Working directory

### ISSUE THREAD

**Issue by MarvinKweyu** [diogocavilha/fancy-git#41]
Hey @diogocavilha , first of all, I love the repo. :clap: 
Is there a way to not show the current working directory as the full path ? For instance, my directory would normally appear as below,
```
[marvin@marvin-pc MyScripts]$ 
```
However, with every path that I get into the line keeps getting longer and longer. 
```bash
marvin@marvin-pc   /long/path/to/some/random/directory/somewhere/fancy-git  master 
```
I may just need the current directory displayed. I followed the definition ` current_dir=$(pwd)`. Can this be used with `basename`?

**Comment by diogocavilha** [comment]
Hi, @MarvinKweyu , thank you for using the fancygit tool. That makes me glad to know it is being useful.

I totally understand the problem you are reporting.

In this case, I wonder if it is ok to create some kind of configuration which informs fancygit to show only the current folder. What do you think of it?

I mean, something like.

```bash
fancygit --fullpath-enable
```

and

```bash
fancygit --fullpath-disable
```

Please, let me know what you think of that possibility.

**Comment by MarvinKweyu** [comment]
That would be feasible. Would provide a much cleaner display. In this case, this would work much like the themes being used except it will use either `relative` or `absolute paths`. We could get started on this in a `dev branch`

**Comment by diogocavilha** [comment]
Hello @MarvinKweyu 

That feature is done! The PR is open because I'm still testing it, but I'm about to make that new release.

**Comment by diogocavilha** [comment]
After updating it. It will show a bash warning, informing that the `app_config` file was not found.

You can reload the terminal in order to load the fancygit new commands and run `fancygit --config-reset`, so it solves the problem ;)

**Comment by MarvinKweyu** [comment]
Worked like a charm @diogocavilha ..Thums up :+1:
