### ISSUE TITLE
fancygit human single line?

### ISSUE THREAD

**Issue by AttilaTheHen** [diogocavilha/fancy-git#45]
It's not shown in the examples, so I was just wondering - is there a `fancygit human` that's single-line? Would love to see that!

**Comment by diogocavilha** [comment]
Hello, @AttilaTheHen 

I've been playing with that idea few days ago. But I was not sure if it would be good.

Now you just made me start thinking on that again, hehe!

I think I'll implement a `single-line` mode for the `human*` styles.

**Comment by AttilaTheHen** [comment]
Awesome, I'll be looking forward to that! This project looks great 👍

**Comment by diogocavilha** [comment]
Thank you!!!
