### ISSUE TITLE
Alias gdb conflicts with gdb debugger

### ISSUE THREAD

**Issue by jfalcou** [diogocavilha/fancy-git#46]
The gdb alias prevents the gdb command to be run. 
Could the alias be made optional or at least can we opt out of using them but keep the prompt?

**Comment by diogocavilha** [comment]
Hello @jfalcou 

I'll try to give that a solution this weekend.

Thank you for reporting that!

**Comment by diogocavilha** [comment]
Hello @jfalcou 

The easiest way to solve that, without changing too much, is adding an extra g at the beginning of the alias.

So `gdb` becomes `ggdb`
