### ISSUE TITLE
grep is failing

### ISSUE THREAD

**Issue by jthalliley** [diogocavilha/fancy-git#47]
As you can see below, I just re-installed fancy-git, and there's an issue with a grep command in the fancy-git.  It seems that "-P" is the issue ... Perl style regex's are experimental and apparently not available on MacOS.

![image](https://user-images.githubusercontent.com/11047539/69880820-04ea9480-1299-11ea-8dfe-a9da54d7ac07.png)

**Comment by jthalliley** [comment]
Here's a better screenshot, after I changed fonts to

**Comment by jthalliley** [comment]
Closed by mistake.

**Comment by jthalliley** [comment]
I was able to resolve this by doing:

`brew install grep
`
and adding` /usr/local/opt/grep/libexec/gnubin `to my `PATH` ahead of `/usr/bin`.

**Comment by diogocavilha** [comment]
I wonder if the `grep` command would work properly even without the `-P` parameter. This way you should not worry

**Comment by diogocavilha** [comment]
I've just repopened this issue because I know how to solve that.

I'll change the way some RegExp are formed, so I won't need the `-P` parameter.

**Comment by diogocavilha** [comment]
Hi @jthalliley 

I've just reopened this issue because I know how to solve that.

I'll change the way some RegExp are formed here, so I won't need the `-P` anymore.

Even though your workaround will solve some problems with a few aliases as well.

**Comment by jthalliley** [comment]
Cool thx.

**Comment by superboo0311** [comment]
i already install grep and also insert before and it's not solve probem 
my PATH : 
/usr/local/opt/grep/libexec/gnubin
:/usr/local/bin
:/usr/bin
:/bin
:/usr/sbin
:/sbin
:/Library/TeX/texbin
:/Library/Apple/usr/bin
<img width="682" alt="Screen Shot 2022-02-12 at 12 56 23 PM" src="https://user-images.githubusercontent.com/60676245/153722519-0f79d1f0-80c8-4eac-b3a9-d67bec7c0acb.png">

**Comment by diogocavilha** [comment]
@superboo0311 

I'm so sorry for that.

I've been thinking about using grep without that option. It seems to have lots of issues when using Mac OS.

I'll try to solve that on next version.

**Comment by monicaluodialpad** [comment]
Having issue like @imtiendat0311  mentioned here

**Comment by henhal** [comment]
`brew install grep` followed by `export PATH="/opt/homebrew/opt/grep/libexec/gnubin:$PATH"` first in my `~/.bash_profile` did the thing for me.
