### ISSUE TITLE
sed is failing

### ISSUE THREAD

**Issue by jthalliley** [diogocavilha/fancy-git#48]
when I try to use  `fancygit double-line`, I get the error below:

![image](https://user-images.githubusercontent.com/11047539/69887372-9c111580-12b4-11ea-856c-d2fb6ba4dc9a.png)

**Comment by diogocavilha** [comment]
Wow! That is a new one!

What if you run `fancygit --config-reset`? Does it solve the problem?

**Comment by jthalliley** [comment]
The good news is that now `fancygit double-line` does take effect, but I still get the sed error.

**Comment by jthalliley** [comment]
If I brew install gnu-sed like I did for grep, I can get past the sed error, but `fancygit double-line `has no effect.

**Comment by diogocavilha** [comment]
Humm, ok. Please let me know if it solves the bug. If so, I'll put that solution on troubleshooting session too.

**Comment by jthalliley** [comment]
I see nothing odd about your sed commands ... `fancygit` has been working great until I just upgraded.

**Comment by jthalliley** [comment]
BTW:  Just bought you a coffee or two.

**Comment by diogocavilha** [comment]
Oh man! Thank you so much! I really appreciate that!!!
