### ISSUE TITLE
Choosing a different style fails

### ISSUE THREAD

**Issue by jthalliley** [diogocavilha/fancy-git#62]
$. fancygit double-line

yields this error:

sed: 1: "/Users/tomhalliley/.fan ...": undefined label 'omhalliley/.fancy-git/app_config'

If I put set -x in fg_update_app_config, I get:

+ sed -i 's/style:.*/style:fancy-double-line/' /Users/tomhalliley/.fancy-git/app_config
sed: 1: "/Users/tomhalliley/.fan ...": undefined label 'omhalliley/.fancy-git/app_config'

This occurs for any attempted configuration change.

**Comment by jthalliley** [comment]
Contents of app_config:

$. cat /Users/tomhalliley/.fancy-git/app_config
style:fancy-double-line
show-full-path:false

**Comment by diogocavilha** [comment]
Hello, @jthalliley 

Have you tried installing the `gnu-sed`? It seems to be a mac issue.

**Comment by jthalliley** [comment]
I did install gnu sed ... that seems to work :)

**Comment by diogocavilha** [comment]
Great! That's an issue with the `sed` command on mac.
