### ISSUE TITLE
double-line not working correctly

### ISSUE THREAD

**Issue by jthalliley** [diogocavilha/fancy-git#63]
double-line seems not to be putting the prompt on the next line.

![image](https://user-images.githubusercontent.com/11047539/75354763-84c5d200-587b-11ea-9ec5-d2898ba05d7d.png)

**Comment by diogocavilha** [comment]
Hello, @jthalliley 

I'm trying to realize what's going on! 
Doesn't that work even if you restar the terminal session?

**Comment by jthalliley** [comment]
Yes, I can restart iTerm2 and the double-line is not working as expected.

**Comment by jthalliley** [comment]
None of the double-line styles are working :(

**Comment by jthalliley** [comment]
I tried installing gnu-grep as well, but to no avail :(

**Comment by jthalliley** [comment]
BTW:  I'm happy to be your Mac OS tester, if want me to try some things.

**Comment by diogocavilha** [comment]
Oh! Great! Thank you too much!

**Comment by jthalliley** [comment]
I got things working :)
Once I moved sourcing prompt.sh to the bottom of my .bashrc, all is good.

**Comment by diogocavilha** [comment]
@jthalliley 

Oh man! Good news! Now that makes sense!!!
I'm gonna add a section on readme, explaining this config detail.

**Comment by diogocavilha** [comment]
@all-contributors please add @jthalliley for financial
