### ISSUE TITLE
Standard grep command fails on MacOS

### ISSUE THREAD

**Issue by pandel** [diogocavilha/fancy-git#68]
Hi!

The perl style grep -ioP commands should be reworked. They don't work in MacOS anymore.

See: https://stackoverflow.com/questions/16658333/grep-p-no-longer-works-how-can-i-rewrite-my-searches

Regards,
Holger

**Comment by diogocavilha** [comment]
Hello, @pandel 

Doesn't that work even if you `brew install grep`?

**Comment by pandel** [comment]
Hey @diogocavilha! I do and I hope, you too! Not too obvious these days...

That's a hint, I didn't try that. Usually I do not replace programs belonging to the main OS with other versions if I don't have to. The same is for sed, btw. It is also not working correctly.

But perhaps I'll replace them with the homebrew versions.

Thanks. I consider this as solved, even though I am not sure, if I'll use the brew versions or not ;-)

**Comment by diogocavilha** [comment]
@pandel 
Yes, things are harder lately.

You're right, I'll add this hint on readme file.
Please, let me know if any related bug shows up.

Thank you!

**Comment by diogocavilha** [comment]
Oh! I've just seen it is already there =D

Take a look... https://github.com/diogocavilha/fancy-git#problems-with-grep-command

**Comment by pandel** [comment]
Yes, you are right, I overlooked those entries, too :-)!

I did "brew install grep  gnu-sed" right now and things are a bit more delicate, I think.

Both, grep and sed, are installed as "ggrep" and "gsed" to separate from the system default. Generally, I think it would be wise to keep this separation working instead of adding the necessary PATH changes.

Nevertheless, I'll add the PATH parts to my bash profile and see if it introduces any problems.

**Comment by pandel** [comment]
BTW, there is still a single error if you issue "fancygit" without any parameter:

`/Users/myuser/.fancy-git/commands.sh: line 203: return: can only "return" from a function or sourced script`

Just remove the "return" in the line and everything is fine, at least under Mac OS :-) - I don't think it is necessary on Linux either.

**Comment by diogocavilha** [comment]
> BTW, there is still a single error if you issue "fancygit" without any parameter:
> 
> `/Users/myuser/.fancy-git/commands.sh: line 203: return: can only "return" from a function or sourced script`
> 
> I am still using bash, not zsh! Just removed the "return" in the line and everything is fine, at least under Mac OS :-) - I don't think it is necessary on Linux either.

Yes, it seems to be a Mac issue. I've tested it here and nothing happens. Anyway, I'm gonna release this fix on next version, which is just around the corner! Thank you for that one!

Btw... could you please, open a new issue for that one?

**Comment by pandel** [comment]
Sure, here it comes: https://github.com/diogocavilha/fancy-git/issues/69

**Comment by diogocavilha** [comment]
> Sure, here it comes: #69

Thank you so much!
