### ISSUE TITLE
Config option to hide current user

### ISSUE THREAD

**Issue by svenfinke** [diogocavilha/fancy-git#72]
I'd like to hide the machine name and my current user on my local machine, but I can't find any option for that and the scripts don't look like something like that is supported... Did I miss something or is a feature like that planned?

**Comment by diogocavilha** [comment]
Hello @svenfinke, unfortunately FancyGit doesn't support this config yet, but I'm aware of it. It'll be included on next versions.

Thanks.

**Comment by diogocavilha** [comment]
It's under test already

**Comment by diogocavilha** [comment]
@all-contributors please add @svenfinke for ideas
