### ISSUE TITLE
/var/log/messages picking up an error when using fancygit

### ISSUE THREAD

**Issue by romunov** [diogocavilha/fancy-git#74]
Looking at `/var/log/messages` I noticed that on every executed command in the terminal, system reports an error. This is the output when I run `logger HERE`:

```
Sep 12 10:34:55 mucek romunov[89777]: HERE
Sep 12 10:34:55 mucek journal[19938]: terminal_screen_shell_preexec: assertion '!priv->between_preexec_and_precmd' failed
```

If I uninstall fancygit or use `tmux`, the error is not present.

```
Sep 12 10:37:19 mucek romunov[90043]: FROM TMUX OK
```

I'm on

```
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 31 (Thirty One)
Release:	31
Codename:	ThirtyOne
```

and use the default gnome terminal.

This is very low priority, was just curious if you have any information why this might be happening?

**Comment by diogocavilha** [comment]
Hi, @romunov 

That's interesting. I don't have any informations about that behavior yet. 
Are you using tmux?

**Comment by romunov** [comment]
I generally don't use tmux, but found (lack of) this behavior in it just by fiddling around.

**Comment by diogocavilha** [comment]
Hi, @romunov. Hope you are doing good.

I am closing this issue as it is more a curiosity, ok?
