### ISSUE TITLE
"No such file or directory" on all bash commands

### ISSUE THREAD

**Issue by noconsulate** [diogocavilha/fancy-git#84]
Running Manjaro KDE fully updated. 

I was prompted by fancy git to install the latest version so I pushed 'y'. I believe it installed version v6.4.2.

Afterward I was getting a "No such file or directory" with every Bash command. (Sorry, I can't be more specific as I lost the terminal window I was using). I decided it wasn't worth trying to fix so I used the uninstall commands from the readme. Now when I start a new terminal window I still get this every time: 
"bash: /home/janssen/.fancy-git/prompt.sh: No such file or directory"

I doubt it will be hard to fix it but it's a PITA.

**Comment by noconsulate** [comment]
For the sake of completeness, this line was left in my .bash_profile after using your uninstall script:

. ~/.fancy-git/prompt.sh

Hope that helps!

**Comment by diogocavilha** [comment]
Hi @noconsulate 

Thank you for creating that issue.
It was bug really.
