### ISSUE TITLE
After update to the latest version ( v6.4.4), error message is shown after every command finished.

### ISSUE THREAD

**Issue by tan-wei** [diogocavilha/fancy-git#89]
After update to the latest version ( v6.4.4), error message is shown after every command finished. For example:
```console
winterreise@winterreise-virtualbox  $  ~/DemoProject/C++Cookbook/build/src  ls
CMakeFiles  Main-0.log  None-1.log  cmake_install.cmake  recepie
bash: [: !=: unary operator expected
winterreise@winterreise-virtualbox  $  ~/DemoProject/C++Cookbook/build/src  
```

I use Manjaro with BASH.

**Comment by tan-wei** [comment]
I confirm that v6.4.3 works well in my computer.

**Comment by diogocavilha** [comment]
Oh! I'm so sorry for that.

This has been fixed already on `v6.4.5`.

Please, run `fancygit update` to get that fixed.

Thank you for the issue. And, please, let me know if it works for both of you.

Regards!

**Comment by BinaryKitten** [comment]
thanks @diogocavilha - 6.4.5 seems to fixed the issue.

**Comment by tan-wei** [comment]
Thanks very much. v6.4.5 seems OK for me. The issue should be closed.
