### ISSUE TITLE
Proposal of adding additional prompt for showing current time

### ISSUE THREAD

**Issue by jtrupina** [diogocavilha/fancy-git#91]
Many users (as well as me) like to have current time in terminal when running commands.

What about possibility that we extend this with another prompt but for current time and which should be configurable as well.

Currently, PS1 is defined like: `PS1="${prompt_user}${prompt_symbol}${prompt_path} "`

My proposal is to have something like this:

 `PS1="${prompt_time}${prompt_user}${prompt_symbol}${prompt_path} "`

Then, we could have in `app_config` configured for example like this:

```
show-time: true
time-format: \D{%H:%M:%S}
```

If this proposal makes sense I'm more than glad to open PR for this.

**Comment by jtrupina** [comment]
@diogocavilha Here is the PR ready for review: #92

**Comment by diogocavilha** [comment]
Thanks @jtrupina.

I'm closing this thread once the feature has been merged already.
