### ISSUE TITLE
`fancygit --full-path-disable` does not work

### ISSUE THREAD

**Issue by r-shafi** [diogocavilha/fancy-git#95]
typing this shows the same result as `fancygit -h`

**Comment by diogocavilha** [comment]
Hi, @r-shafi 

It seems you've found out a mistake on helper. I've just checked it here and the right command in this case is `fancygit --enable-full-path` or `fancygit --disable-full-path`

So sorry for that. A new version with a correction on helper text is just around the corner!

**Comment by diogocavilha** [comment]
That has been fixed on `v6.4.8`

**Comment by diogocavilha** [comment]
@r-shafi 

That has been fixed on `v6.4.8`. (only the help text has been changed).

**Comment by r-shafi** [comment]
Thank you
